[package]
name = "test-analyzer"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>", "Andreas Doerr <0xad@gmx.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["cargo", "derive"] }
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
explugin-example = { path= "../../plugins/explugin-example" }
libpcap-analyzer = { path= "../../libpcap-analyzer" }
libpcap-tools = { path= "../../libpcap-tools" }
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
lz4 = "1.23"
serde_json = "1.0"
simplelog = { version="0.12", default-features = false }
xz2 = "0.1"
