[workspace]
members = [
  "plugins/explugin-example",
  "libpcap-analyzer",
  "libpcap-tools",
  #"pcap-analyzer",
  #"pcap-cli",
  "examples/pako-info",
  #"examples/test-analyzer",
  #"pcap-rewrite",
  #"test-analyzer",
]

[patch.crates-io]
# pcap-parser = { git="https://github.com/rusticata/pcap-parser" }
# pcap-parser = { path="../pcap-parser" }
