[workspace]
members = [
  #"pcap-analyzer",
  #"pcap-cli",
  "examples/pako-info",
  "examples/test-analyzer",
  "pako-core",
  "pako-tools",
  "plugins/explugin-example",
  "examples/pako-rewrite",
]

[patch.crates-io]
# pcap-parser = { git="https://github.com/rusticata/pcap-parser" }
# pcap-parser = { path="../pcap-parser" }
